#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Migrate the database
python manage.py migrate
# Create default super user
python manage.py createsuperuser --noinput
# Run the Django development server
exec python manage.py runserver 0.0.0.0:8000
