groups:
  - name: 'django'
    rules:
      - alert: 'DjangoMigrationsUnapplied'
        annotations:
          description: 'The job {{ $labels.job }} has unapplied migrations.'
          summary: 'Django has unapplied migrations.'
        expr: |
          sum(
            django_migrations_unapplied_total{
              job=~"django"
            }
          ) by (namespace, job)
          > 0
        for: '15m'
        labels:
          'severity': 'warning'
      - alert: 'DjangoDatabaseException'
        annotations:
          description: 'The job {{ $labels.job }} has hit the database exception {{ $labels.type }}.'
          summary: 'Django database exception.'
        expr: |
          sum (
            increase(
              django_db_errors_total{
                job=~"django"
              }[10m]
            )
          ) by (type, namespace, job)
          > 0
        labels:
          'severity': 'info'
      - alert: 'DjangoHighHttp4xxErrorRate'
        annotations:
          description: 'More than 5% HTTP requests with status 4xx for {{ $labels.job }}/{{ $labels.view }} the past 5m.'
          summary: 'Django high HTTP 4xx error rate.'
        expr: |
          sum(
            rate(
              django_http_responses_total_by_status_view_method_total{
                job=~"django",
                status=~"^4.*",
                view!~"<unnamed view>|health_check:health_check_home|prometheus-django-metrics"
              }[5m]
            )
          )  by (namespace, job, view)
          /
          sum(
            rate(
              django_http_responses_total_by_status_view_method_total{
                job=~"django",
                view!~"<unnamed view>|health_check:health_check_home|prometheus-django-metrics"
              }[5m]
            )
          )  by (namespace, job, view)
          * 100 > 5
        for: '1m'
        labels:
          'severity': 'warning'
      - alert: 'DjangoHighHttp5xxErrorRate'
        annotations:
          description: 'More than 5% HTTP requests with status 5xx for {{ $labels.job }}/{{ $labels.view }} the past 5m.'
          summary: 'Django high HTTP 5xx error rate.'
        expr: |
          sum(
            rate(
              django_http_responses_total_by_status_view_method_total{
                job=~"django",
                status=~"^5.*",
                view!~"<unnamed view>|health_check:health_check_home|prometheus-django-metrics"
              }[5m]
            )
          )  by (namespace, job, view)
          /
          sum(
            rate(
              django_http_responses_total_by_status_view_method_total{
                job=~"django",
                view!~"<unnamed view>|health_check:health_check_home|prometheus-django-metrics"
              }[5m]
            )
          )  by (namespace, job, view)
          * 100 > 5
        for: '1m'
        labels:
          'severity': 'warning'
