global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'django_app'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['django:8000']
  - job_name: flower
    static_configs:
      - targets: ['flower:5555']
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']
rule_files:
  - 'prometheus-alerts.yaml'
  - 'prometheus-alerts-celery.yaml'
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
